### ISSUE TITLE
This lib needs polyfills in IE

### ISSUE THREAD

**Issue by fiftyk** [ProteinsWebTeam/domain-gfx#1]
First，Thank you for your work。

In my project，i use this lib，and found some errors in IE，if i don't fix the source codes, we need the polyfills in the project，maybe something like the following

`<script src="https://polyfill.io/v2/polyfill.js?features=Set,Object.entries,Symbol,Array.prototype.@@iterator,Element.prototype.dataset"></script>`

but, even use the polyfills， i found the text in the rectange will not be render，because of the polyfill of `Element.prototype.dataset` seems not work correct.

**Comment by aurel-l** [comment]
In the end I did some modifications to add support for IE10 (not below).
The polyfill.io approach didn't work for me so I added the polyfills in the codebase for the examples, and I'm now generating 2 bundles, one with the polyfills (called "legacy"), and one without.
